package ar.com.encontrarpersonas.data

import android.content.Context
import ar.com.encontrarpersonas.App

/**
 * MIT License
 *
 * Copyright (c) 2017 Proyecto Encontrar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
object UserRepository {

    private val SHARED_PREFERENCES_USER = "UserPreferences"
    private val FIELD_API_AUTH_TOKEN = "apiAuthToken"
    private val FIELD_FIREBASE_NOTIFICATIONS_TOKEN = "firebaseNotificationsToken"
    private val FIELD_USER_FIRST_NAME = "userFirstName"
    private val FIELD_USER_LAST_NAME = "userLastName"
    private val FIELD_USER_NATIONAL_ID = "userNationalId"
    private val FIELD_SETTINGS_NOTIFICATIONS_TRAY = "settingsNotificationsTray"
    private val FIELD_SETTINGS_NOTIFICATIONS_WALLPAPER = "settingsNotificationsWallpaper"
    private val FIELD_SETTINGS_NOTIFICATIONS_LOCKSCREEN = "settingsNotificationsLockscreen"

    // Since tokens are used frequently, screen them in memory for faster access
    private var apiAuthToken: String? = null
    private var firebaseNotificationsToken: String? = null

    // Using lazy initialization to obtain shared preferences in case it is not necessary
    private val sharedPreferences by lazy {
        App.sInstance.getSharedPreferences(
                SHARED_PREFERENCES_USER,
                Context.MODE_PRIVATE)
    }

    /**
     * Returns the token required for the authenticated endpoints of Encontrar API.
     */
    fun getApiAuthToken(): String? {
        return if (apiAuthToken != null)
            apiAuthToken
        else
            sharedPreferences.getString(FIELD_API_AUTH_TOKEN, null)
    }

    /**
     * Sets asynchronously the token required for the authenticated endpoints of Encontrar API.
     */
    fun setApiAuthToken(token: String) {
        apiAuthToken = token
        sharedPreferences.edit().putString(FIELD_API_AUTH_TOKEN, token).apply()
    }

    /**
     * Returns Firebase's device token for sending push notifications to the running device.
     */
    fun getFirebaseNotificationsToken(): String? {
        return if (firebaseNotificationsToken != null)
            firebaseNotificationsToken
        else
            sharedPreferences.getString(FIELD_FIREBASE_NOTIFICATIONS_TOKEN, null)
    }

    /**
     *  Sets asynchronously Firebase's device token for sending push notifications
     *  to the running device.
     *
     *  Note that the token should be generated by Firebase. It doesn't make much sense to set
     *  any other custom token here.
     */
    fun setFirebaseNotificationsToken(token: String) {
        firebaseNotificationsToken = token
        sharedPreferences.edit().putString(FIELD_FIREBASE_NOTIFICATIONS_TOKEN, token).apply()
    }

    /**
     * Returns the user's first name
     */
    fun getUserFirstName() : String? {
        return sharedPreferences.getString(FIELD_USER_FIRST_NAME, null)
    }

    /**
     * Sets asynchronously the user's first name
     */
    fun setUserFirstName(firstName : String) {
        sharedPreferences.edit().putString(FIELD_USER_FIRST_NAME, firstName).apply()
    }
}